# MinePanel Setup Wizard — Windows (PowerShell 5.1+)
# Run with: powershell -ExecutionPolicy Bypass -File setup.ps1

$ErrorActionPreference = 'Stop'

# ── Colors ────────────────────────────────────────────────────────────────────
function Write-Step   { param($n, $msg) Write-Host "`n[ $n ] $msg" -ForegroundColor Cyan }
function Write-Ok     { param($msg) Write-Host "  [OK] $msg" -ForegroundColor Green }
function Write-Warn   { param($msg) Write-Host "  [!]  $msg" -ForegroundColor Yellow }
function Write-Fail   { param($msg) Write-Host "  [X]  $msg" -ForegroundColor Red; exit 1 }
function Write-Ask    { param($msg) Write-Host "  [?]  $msg " -ForegroundColor White -NoNewline }

# ── Header ────────────────────────────────────────────────────────────────────
Clear-Host
Write-Host ""
Write-Host "  +----------------------------------------------------------+" -ForegroundColor Green
Write-Host "  |                                                          |" -ForegroundColor Green
Write-Host "  |   __  __ _            ____                  _           |" -ForegroundColor Green
Write-Host "  |  |  \/  (_)_ __  ___|  _ \ __ _ _ __   ___| |          |" -ForegroundColor Green
Write-Host "  |  | |\/| | | '_ \/ _ \ |_) / _` | '_ \ / _ \ |         |" -ForegroundColor Green
Write-Host "  |  | |  | | | | | |  __/  __/ (_| | | | |  __/ |         |" -ForegroundColor Green
Write-Host "  |  |_|  |_|_|_| |_|\___|_|   \__,_|_| |_|\___|_|         |" -ForegroundColor Green
Write-Host "  |                                                          |" -ForegroundColor Green
Write-Host "  |      Self-hosted Minecraft Server Manager               |" -ForegroundColor Green
Write-Host "  |              Setup Wizard -- Windows                    |" -ForegroundColor Green
Write-Host "  |                                                          |" -ForegroundColor Green
Write-Host "  +----------------------------------------------------------+" -ForegroundColor Green
Write-Host ""

# ── Step 1: Prerequisites ─────────────────────────────────────────────────────
Write-Step "1/3" "Checking prerequisites"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  Write-Fail "Docker not found. Install Docker Desktop from https://www.docker.com/products/docker-desktop/"
}

try { docker info 2>&1 | Out-Null } catch {
  Write-Fail "Docker daemon not running. Open Docker Desktop and wait for it to start."
}

try { docker compose version 2>&1 | Out-Null } catch {
  Write-Fail "Docker Compose plugin not found. Update Docker Desktop."
}

$dockerVer = (docker --version) -replace '.*?(\d+\.\d+\.\d+).*', '$1'
Write-Ok "Docker $dockerVer + Compose ready"

# ── Step 2: Configuration ─────────────────────────────────────────────────────
Write-Step "2/3" "Configuration"

$skipEnv = $false
if (Test-Path ".env") {
  Write-Warn ".env already exists."
  Write-Ask "Overwrite it? [y/N]"
  $ans = Read-Host
  if ($ans -match '^[Yy]$') {
    Remove-Item -Path ".env" -Force
  } else {
    $skipEnv = $true
    # reuse the existing deployment: load its DOMAIN for the launch step
    $domain = ((Get-Content ".env") | Where-Object { $_ -match '^DOMAIN=' } | Select-Object -First 1)
    if ($domain) { $domain = ($domain -split '=', 2)[1].Trim().Trim('"') }
    if ([string]::IsNullOrWhiteSpace($domain)) {
      Write-Fail ".env exists but DOMAIN is empty; fix .env or overwrite it"
    }
    if ($domain -notmatch '^[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?$') {
      Write-Fail ".env exists but DOMAIN is not a bare hostname; fix .env or overwrite it"
    }
  }
}

if (-not $skipEnv) {
  Write-Host ""
  Write-Host "  Enter your domain for automatic HTTPS (e.g. panel.example.com)."
  Write-Host "  A non-empty bare hostname is required (no scheme, port, or path)."

  $domain = $null
  for ($i = 1; $i -le 3; $i++) {
    Write-Ask "Domain:"; $domain = (Read-Host).Trim()
    if ($domain -match '^[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?$') { break }
    Write-Warn "DOMAIN must be a bare hostname"
    $domain = $null
  }
  if ([string]::IsNullOrWhiteSpace($domain)) { Write-Fail "DOMAIN is required" }

  Write-Ask "Frontend CORS origin [https://minepanel.xyz]:"; $corsOrigin = Read-Host
  if ([string]::IsNullOrWhiteSpace($corsOrigin)) { $corsOrigin = 'https://minepanel.xyz' }

  function New-HexSecret { param([int]$bytes = 32)
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $buf = [byte[]]::new($bytes)
    $rng.GetBytes($buf)
    return ($buf | ForEach-Object { $_.ToString('x2') }) -join ''
  }

  $jwtSecret      = New-HexSecret 32
  $pgPassword     = New-HexSecret 24
  $encryptionKey  = New-HexSecret 32
  $mcDataPathHost = Join-Path $env:USERPROFILE '.minepanel' 'mc-data'
  $timestamp      = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

  $envContent = @"
# Generated by setup.ps1 -- $timestamp

DOMAIN=$domain
CORS_ORIGIN=$corsOrigin
MINEPANEL_IMAGE=ghcr.io/minepanelproject/minepanel-backend:latest

POSTGRES_PASSWORD=$pgPassword
DATABASE_URL="postgresql://minepanel:$pgPassword@postgres:5432/minepanel"

JWT_SECRET=$jwtSecret
JWT_EXPIRES_IN="15m"
JWT_REFRESH_EXPIRES_IN="7d"

REQUIRE_ADMIN_APPROVAL=true
LOGIN_THROTTLE_LIMIT=5
LOGIN_THROTTLE_TTL_MS=10000

ENCRYPTION_KEY=$encryptionKey

NODE_ENV=production
PORT=3000
PANEL_NAME="MinePanel"

DOCKER_SOCKET="/var/run/docker.sock"
DOCKER_NETWORK="minepanel_network"
MC_DATA_PATH_HOST=$mcDataPathHost
MC_DATA_PATH="/mc-data"
MC_DATA_BIND_SOURCE=$mcDataPathHost
MC_PORT_MIN=25565
MC_PORT_MAX=25665
MIN_FREE_DISK_MB=2048
MAX_MEMORY_RATIO=0.90
STOP_WARN_SECONDS=30
"@

  Set-Content -Path ".env" -Value $envContent -Encoding UTF8

  # secrets file: owner-only ACL (Windows: remove inherited, grant current user)
  icacls ".env" /inheritance:r /grant:r "$env:USERNAME:(F)" | Out-Null
  if ($LASTEXITCODE -ne 0) {
    Remove-Item -Path ".env" -Force -ErrorAction SilentlyContinue
    Write-Fail "Could not restrict .env permissions; refusing to continue with world-readable secrets"
  }

  Write-Ok ".env generated"
}

# ── Step 3: Launch ────────────────────────────────────────────────────────────
Write-Step "3/3" "Launching MinePanel"

docker compose pull
docker compose up -d

$base = "https://$domain"

Write-Host ""
Write-Host "  MinePanel is starting!" -ForegroundColor Green
Write-Host ""
Write-Host "  API:    $base/api" -ForegroundColor Cyan
Write-Host "  Docs:   $base/docs" -ForegroundColor Cyan
Write-Host "  Health: $base/health" -ForegroundColor Cyan
Write-Host ""
Write-Host "  First-run admin setup:"
Write-Host "  $base/api/setup/init" -ForegroundColor Cyan
Write-Host ""

$maxAttempts = 30
$reachable = $false
for ($i = 1; $i -le $maxAttempts; $i++) {
  try {
    Invoke-RestMethod -Uri "$base/health" -Method GET -ErrorAction Stop | Out-Null
    $reachable = $true
    break
  } catch {
    if ($i -eq $maxAttempts) { break }
    Start-Sleep -Seconds 2
  }
}

if ($reachable) {
  Write-Ok "HTTPS health check passed ($base/health)"
} else {
  Write-Warn "HTTPS health check did not become reachable within the timeout"
  Write-Host ""
  docker compose ps
  Write-Host ""
  docker compose logs --tail 50 nestjs
  Write-Fail "Deployment failed"
}

Write-Ask "Open setup page in browser? [Y/n]"
$ans = Read-Host
if ($ans -notmatch '^[Nn]$') {
  Start-Process "$base/api/setup/init"
}
