# MinePanel Setup Wizard — Windows (PowerShell 5.1+)
# Run with: powershell -ExecutionPolicy Bypass -File setup.ps1

$ErrorActionPreference = 'Stop'

# ── Colors ────────────────────────────────────────────────────────────────────
function Write-Step   { param($n, $msg) Write-Host "`n[ $n ] $msg" -ForegroundColor Cyan }
function Write-Ok     { param($msg) Write-Host "  [OK] $msg" -ForegroundColor Green }
function Write-Warn   { param($msg) Write-Host "  [!]  $msg" -ForegroundColor Yellow }
function Write-Fail   { param($msg) Write-Host "  [X]  $msg" -ForegroundColor Red; exit 1 }
function Write-Ask    { param($msg) Write-Host "  [?]  $msg " -ForegroundColor White -NoNewline }

# ── Header ────────────────────────────────────────────────────────────────────
Clear-Host
Write-Host ""
Write-Host "  +----------------------------------------------------------+" -ForegroundColor Green
Write-Host "  |                                                          |" -ForegroundColor Green
Write-Host "  |   __  __ _            ____                  _           |" -ForegroundColor Green
Write-Host "  |  |  \/  (_)_ __  ___|  _ \ __ _ _ __   ___| |          |" -ForegroundColor Green
Write-Host "  |  | |\/| | | '_ \/ _ \ |_) / _` | '_ \ / _ \ |         |" -ForegroundColor Green
Write-Host "  |  | |  | | | | | |  __/  __/ (_| | | | |  __/ |         |" -ForegroundColor Green
Write-Host "  |  |_|  |_|_|_| |_|\___|_|   \__,_|_| |_|\___|_|         |" -ForegroundColor Green
Write-Host "  |                                                          |" -ForegroundColor Green
Write-Host "  |      Self-hosted Minecraft Server Manager               |" -ForegroundColor Green
Write-Host "  |              Setup Wizard -- Windows                    |" -ForegroundColor Green
Write-Host "  |                                                          |" -ForegroundColor Green
Write-Host "  +----------------------------------------------------------+" -ForegroundColor Green
Write-Host ""

# ── Step 1: Prerequisites ─────────────────────────────────────────────────────
Write-Step "1/4" "Checking prerequisites"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  Write-Fail "Docker not found. Install Docker Desktop from https://www.docker.com/products/docker-desktop/"
}

try { docker info 2>&1 | Out-Null } catch {
  Write-Fail "Docker daemon not running. Open Docker Desktop and wait for it to start."
}

try { docker compose version 2>&1 | Out-Null } catch {
  Write-Fail "Docker Compose plugin not found. Update Docker Desktop."
}

$dockerVer = (docker --version) -replace '.*?(\d+\.\d+\.\d+).*', '$1'
Write-Ok "Docker $dockerVer + Compose ready"

# ── Step 2: Release check ─────────────────────────────────────────────────────
Write-Step "2/4" "Checking release"

$currentTag = (git describe --tags --exact-match HEAD 2>$null) ?? "dev"
try {
  $apiResponse = Invoke-RestMethod "https://api.github.com/repos/MinePanelProject/minepanel-backend/releases/latest"
  $latestTag = $apiResponse.tag_name
} catch { $latestTag = "" }

if ($latestTag -and $currentTag -ne $latestTag) {
  Write-Warn "You are on '$currentTag', latest release is '$latestTag'."
  Write-Ask "Continue anyway? [y/N]"
  $ans = Read-Host
  if ($ans -notmatch '^[Yy]$') { exit 0 }
} else {
  Write-Ok "Running $currentTag"
}

# ── Step 3: Configuration ─────────────────────────────────────────────────────
Write-Step "3/4" "Configuration"

$skipEnv = $false
if (Test-Path ".env") {
  Write-Warn ".env already exists."
  Write-Ask "Overwrite it? [y/N]"
  $ans = Read-Host
  if ($ans -notmatch '^[Yy]$') { $skipEnv = $true }
}

$useCaddy = $false
if (-not $skipEnv) {
  Write-Host ""
  Write-Host "  Enter your domain for automatic HTTPS (e.g. panel.example.com)."
  Write-Host "  Leave blank to run on HTTP port 3000 only."
  Write-Ask "Domain [blank = HTTP only]:"
  $domain = Read-Host

  if ($domain) {
    $useCaddy = $true
    Write-Ok "HTTPS via Caddy for $domain"
  } else {
    Write-Warn "No domain -- panel will be at http://localhost:3000"
  }

  # Generate secrets using .NET crypto (no openssl needed)
  function New-HexSecret { param([int]$bytes = 32)
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $buf = [byte[]]::new($bytes)
    $rng.GetBytes($buf)
    return ($buf | ForEach-Object { $_.ToString('x2') }) -join ''
  }

  $jwtSecret      = New-HexSecret 32
  $pgPassword     = New-HexSecret 24
  $encryptionKey  = New-HexSecret 32
  $timestamp      = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

  $envContent = @"
# Generated by setup.ps1 -- $timestamp

POSTGRES_PASSWORD=$pgPassword
DATABASE_URL="postgresql://minepanel:$pgPassword@postgres:5432/minepanel"

JWT_SECRET=$jwtSecret
JWT_EXPIRES_IN="15m"
JWT_REFRESH_EXPIRES_IN="7d"

REQUIRE_ADMIN_APPROVAL=true
LOGIN_THROTTLE_LIMIT=5
LOGIN_THROTTLE_TTL_MS=10000

ENCRYPTION_KEY=$encryptionKey

DOMAIN=$domain
PORT=3000
NODE_ENV=production
PANEL_NAME="MinePanel"
PANEL_ASSETS_PATH="/panel-assets"

DOCKER_SOCKET="/var/run/docker.sock"
DOCKER_NETWORK="minepanel_network"
MC_DATA_PATH="/mc-data"
MC_PORT_MIN=25565
MC_PORT_MAX=25665
MIN_FREE_DISK_MB=2048
MAX_MEMORY_RATIO=0.90
"@

  Set-Content -Path ".env" -Value $envContent -Encoding UTF8
  Write-Ok ".env generated"
}

# ── Step 4: Launch ────────────────────────────────────────────────────────────
Write-Step "4/4" "Launching MinePanel"

if ($useCaddy) {
  docker compose --profile caddy up -d --build
  $base = "https://$domain"
} else {
  docker compose up -d --build
  $base = "http://localhost:3000"
}

Write-Host ""
Write-Host "  MinePanel is running!" -ForegroundColor Green
Write-Host ""
Write-Host "  API:    $base/api" -ForegroundColor Cyan
Write-Host "  Docs:   $base/docs" -ForegroundColor Cyan
Write-Host "  Health: $base/health" -ForegroundColor Cyan
Write-Host ""
Write-Host "  First-run admin setup:"
Write-Host "  $base/api/setup/init" -ForegroundColor Cyan
Write-Host ""

Write-Ask "Open setup page in browser? [Y/n]"
$ans = Read-Host
if ($ans -notmatch '^[Nn]$') {
  Start-Process "$base/api/setup/init"
}
