#!/usr/bin/env bash
set -euo pipefail

# ─── Colors ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${CYAN}[→]${NC} $*"; }
success() { echo -e "${GREEN}[✔]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*"; exit 1; }

echo -e "${BOLD}"
echo "  __  __ _            ____                  _ "
echo " |  \/  (_)_ __  ___|  _ \ __ _ _ __   ___| |"
echo " | |\/| | | '_ \/ _ \ |_) / _\` | '_ \ / _ \ |"
echo " | |  | | | | | |  __/  __/ (_| | | | |  __/ |"
echo " |_|  |_|_|_| |_|\___|_|   \__,_|_| |_|\___|_|"
echo -e "${NC}"
echo -e " Self-hosted Minecraft server management panel"
echo ""

# ─── 1. Prerequisites ─────────────────────────────────────────────────────────
info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
  error "Docker is not installed. See https://docs.docker.com/engine/install/"
fi

if ! docker compose version &>/dev/null; then
  error "Docker Compose plugin not found. Update Docker or install the plugin."
fi

success "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+' | head -1) + Compose found"

# ─── 2. Release tag check ─────────────────────────────────────────────────────
CURRENT_TAG=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")
LATEST_TAG=$(curl -sf "https://api.github.com/repos/MinePanelProject/minepanel-backend/releases/latest" \
  | grep '"tag_name"' | cut -d'"' -f4 || echo "")

if [ -n "$LATEST_TAG" ] && [ "$CURRENT_TAG" != "$LATEST_TAG" ]; then
  warn "You are on '${CURRENT_TAG:-dev}', latest release is '${LATEST_TAG}'."
  warn "Run: git fetch --tags && git checkout ${LATEST_TAG}"
  echo -n "  Continue anyway? [y/N] "
  read -r CONTINUE
  [[ "$CONTINUE" =~ ^[Yy]$ ]] || exit 0
fi

# ─── 3. Existing .env check ───────────────────────────────────────────────────
if [ -f .env ]; then
  warn ".env already exists."
  echo -n "  Overwrite it? [y/N] "
  read -r OVERWRITE
  [[ "$OVERWRITE" =~ ^[Yy]$ ]] || { info "Skipping .env generation. Running docker compose..."; SKIP_ENV=1; }
fi

if [ "${SKIP_ENV:-0}" = "0" ]; then
  # ─── 4. Domain input ──────────────────────────────────────────────────────
  echo ""
  echo -e " ${BOLD}Domain setup${NC}"
  echo "  Enter your domain for automatic HTTPS (e.g. panel.example.com)."
  echo "  Leave blank to run without HTTPS on port 3000."
  echo -n "  Domain [leave blank to skip]: "
  read -r DOMAIN

  USE_CADDY=0
  if [ -n "$DOMAIN" ]; then
    USE_CADDY=1
    success "HTTPS enabled via Caddy for ${DOMAIN}"
  else
    warn "No domain entered. The panel will be accessible at http://SERVER_IP:3000 (HTTP only)."
  fi

  # ─── 5. Generate secrets ──────────────────────────────────────────────────
  info "Generating secrets..."
  JWT_SECRET=$(openssl rand -hex 32)
  POSTGRES_PASSWORD=$(openssl rand -hex 24)
  ENCRYPTION_KEY=$(openssl rand -hex 32)
  success "Secrets generated"

  # ─── 6. Write .env ────────────────────────────────────────────────────────
  cat > .env <<EOF
# Generated by setup.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ─── Database ─────────────────────────────────────────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL="postgresql://minepanel:${POSTGRES_PASSWORD}@postgres:5432/minepanel"

# ─── JWT ──────────────────────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN="15m"
JWT_REFRESH_EXPIRES_IN="7d"

# ─── Login / Auth ─────────────────────────────────────────────────────────────
REQUIRE_ADMIN_APPROVAL=true
LOGIN_THROTTLE_LIMIT=5
LOGIN_THROTTLE_TTL_MS=10000

# ─── Encryption ───────────────────────────────────────────────────────────────
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# ─── App ──────────────────────────────────────────────────────────────────────
DOMAIN=${DOMAIN}
PORT=3000
NODE_ENV=production
PANEL_NAME="MinePanel"
PANEL_ASSETS_PATH="/panel-assets"

# ─── Docker ───────────────────────────────────────────────────────────────────
DOCKER_SOCKET="/var/run/docker.sock"
DOCKER_NETWORK="minepanel_network"
MC_DATA_PATH="/mc-data"
MC_PORT_MIN=25565
MC_PORT_MAX=25665
MIN_FREE_DISK_MB=2048
MAX_MEMORY_RATIO=0.90
EOF

  success ".env created"
fi

# ─── 7. Launch ────────────────────────────────────────────────────────────────
echo ""
info "Starting MinePanel..."

if [ "${USE_CADDY:-0}" = "1" ]; then
  docker compose --profile caddy up -d --build
else
  docker compose up -d --build
fi

# ─── 8. Done ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}  MinePanel is up!${NC}"
echo ""
if [ "${USE_CADDY:-0}" = "1" ]; then
  echo -e "  Panel backend: ${CYAN}https://${DOMAIN}/api${NC}"
  echo -e "  Swagger docs:  ${CYAN}https://${DOMAIN}/docs${NC}"
  echo -e "  Health check:  ${CYAN}https://${DOMAIN}/health${NC}"
else
  echo -e "  Panel backend: ${CYAN}http://localhost:3000/api${NC}"
  echo -e "  Swagger docs:  ${CYAN}http://localhost:3000/docs${NC}"
  echo -e "  Health check:  ${CYAN}http://localhost:3000/health${NC}"
fi
echo ""
echo "  First-run setup (create admin account):"
if [ "${USE_CADDY:-0}" = "1" ]; then
  echo -e "  ${CYAN}https://${DOMAIN}/api/setup/init${NC}"
else
  echo -e "  ${CYAN}http://localhost:3000/api/setup/init${NC}"
fi
echo ""
