#!/usr/bin/env bash
# MinePanel Setup Wizard — macOS
set -euo pipefail

G='\033[92m'; Y='\033[93m'; R='\033[91m'; C='\033[96m'; B='\033[1m'; X='\033[0m'
W=56

header() {
  clear
  echo -e "${G}${B}"
  echo "  ╔$(printf '═%.0s' $(seq 1 $W))╗"
  echo "  ║$(printf ' %.0s' $(seq 1 $W))║"
  echo "  ║   __  __ _            ____                  _   ║"
  echo "  ║  |  \/  (_)_ __  ___|  _ \ __ _ _ __   ___| |  ║"
  echo "  ║  | |\/| | | '_ \/ _ \ |_) / _\` | '_ \ / _ \ |  ║"
  echo "  ║  | |  | | | | | |  __/  __/ (_| | | | |  __/ |  ║"
  echo "  ║  |_|  |_|_|_| |_|\___|_|   \__,_|_| |_|\___|_|  ║"
  echo "  ║$(printf ' %.0s' $(seq 1 $W))║"
  echo "  ║      Self-hosted Minecraft Server Manager        ║"
  echo "  ║              Setup Wizard — macOS                ║"
  echo "  ║$(printf ' %.0s' $(seq 1 $W))║"
  echo "  ╚$(printf '═%.0s' $(seq 1 $W))╝"
  echo -e "${X}"
}

step()    { echo -e "\n${C}${B}[ $1 ]${X} $2"; }
ok()      { echo -e "  ${G}✔${X} $*"; }
warn()    { echo -e "  ${Y}!${X} $*"; }
fail()    { echo -e "  ${R}✗${X} $*"; exit 1; }
ask()     { echo -en "  ${B}?${X} $1 "; }

header

# ── Step 1: Prerequisites ──────────────────────────────────────────────────────
step "1/4" "Checking prerequisites"

# Docker Desktop check
if ! command -v docker &>/dev/null; then
  fail "Docker not found. Install Docker Desktop from https://www.docker.com/products/docker-desktop/"
fi

if ! docker info &>/dev/null; then
  fail "Docker daemon not running. Open Docker Desktop and wait for it to start."
fi

docker compose version &>/dev/null || fail "Docker Compose plugin not found. Update Docker Desktop."
ok "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+' | head -1) + Compose ready"

# macOS uses /var/run/docker.sock via Docker Desktop VM — no XDG_RUNTIME_DIR needed
ok "Docker socket: /var/run/docker.sock (Docker Desktop)"

# ── Step 2: Release check ──────────────────────────────────────────────────────
step "2/4" "Checking release"

CURRENT=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "dev")
LATEST=$(curl -sf "https://api.github.com/repos/MinePanelProject/minepanel-backend/releases/latest" \
  | python3 -c "import sys,json; print(json.load(sys.stdin).get('tag_name',''))" 2>/dev/null || true)

if [[ -n "$LATEST" && "$CURRENT" != "$LATEST" ]]; then
  warn "You are on '${CURRENT}', latest release is '${LATEST}'."
  ask "Continue anyway? [y/N]"; read -r ANS
  [[ "$ANS" =~ ^[Yy]$ ]] || exit 0
else
  ok "Running ${CURRENT}"
fi

# ── Step 3: Configuration ──────────────────────────────────────────────────────
step "3/4" "Configuration"

SKIP_ENV=0
if [[ -f .env ]]; then
  warn ".env already exists."
  ask "Overwrite it? [y/N]"; read -r ANS
  [[ "$ANS" =~ ^[Yy]$ ]] || SKIP_ENV=1
fi

USE_CADDY=0
if [[ $SKIP_ENV -eq 0 ]]; then
  echo -e "\n  Enter your domain for automatic HTTPS (e.g. panel.example.com)."
  echo    "  Leave blank to run on HTTP port 3000 (local testing)."
  ask "Domain [blank = HTTP only]:"; read -r DOMAIN

  [[ -n "$DOMAIN" ]] && USE_CADDY=1 && ok "HTTPS via Caddy for ${DOMAIN}" \
    || warn "No domain — panel will be at http://localhost:3000"

  # macOS has openssl via LibreSSL, works the same
  JWT_SECRET=$(openssl rand -hex 32)
  POSTGRES_PASSWORD=$(openssl rand -hex 24)
  ENCRYPTION_KEY=$(openssl rand -hex 32)

  cat > .env <<EOF
# Generated by setup-mac.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL="postgresql://minepanel:${POSTGRES_PASSWORD}@postgres:5432/minepanel"

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN="15m"
JWT_REFRESH_EXPIRES_IN="7d"

REQUIRE_ADMIN_APPROVAL=true
LOGIN_THROTTLE_LIMIT=5
LOGIN_THROTTLE_TTL_MS=10000

ENCRYPTION_KEY=${ENCRYPTION_KEY}

DOMAIN=${DOMAIN}
PORT=3000
NODE_ENV=production
PANEL_NAME="MinePanel"
PANEL_ASSETS_PATH="/panel-assets"

DOCKER_SOCKET="/var/run/docker.sock"
DOCKER_NETWORK="minepanel_network"
MC_DATA_PATH="/mc-data"
MC_PORT_MIN=25565
MC_PORT_MAX=25665
MIN_FREE_DISK_MB=2048
MAX_MEMORY_RATIO=0.90
EOF
  ok ".env generated"
fi

# ── Step 4: Launch ─────────────────────────────────────────────────────────────
step "4/4" "Launching MinePanel"

if [[ $USE_CADDY -eq 1 ]]; then
  docker compose --profile caddy up -d --build
  BASE="https://${DOMAIN}"
else
  docker compose up -d --build
  BASE="http://localhost:3000"
fi

echo -e "\n  ${G}${B}MinePanel is running!${X}\n"
echo -e "  API:    ${C}${BASE}/api${X}"
echo -e "  Docs:   ${C}${BASE}/docs${X}"
echo -e "  Health: ${C}${BASE}/health${X}"
echo -e "\n  First-run admin setup:"
echo -e "  ${C}${BASE}/api/setup/init${X}\n"

ask "Open setup page in browser? [Y/n]"; read -r ANS
[[ ! "$ANS" =~ ^[Nn]$ ]] && open "${BASE}/api/setup/init"
